name: Update GitHub Pages branch

on:
  push:
    branches:
      - main

jobs:
  merge-to-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch github-pages branch
        run: |
          git fetch origin github-pages:github-pages

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge main into github-pages
        run: |
          git checkout github-pages
          git merge main --no-edit || true

      - name: Push changes
        run: |
          git push origin github-pages
